/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author tony-
 */
public class FanaticEditView extends javax.swing.JFrame {

    /**
     * Creates new form FanaticEditView
     */
    public FanaticEditView() {
        initComponents();
        setTitle("Plataforma de Editar Fanatico");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAplicarEdit = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNameFanaticEdit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastNameFanaticEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserNameFanaticEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFanaticEdit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbTeamsFanaticEdit = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAplicarEdit.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnAplicarEdit.setText("Aplicar");
        jPanel1.add(btnAplicarEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 160, 60));

        btnReturn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnReturn.setText("Volver");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 160, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Perfil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 113, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Nombre :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 20));

        txtNameFanaticEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFanaticEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtNameFanaticEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Apellido :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, 20));

        txtLastNameFanaticEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameFanaticEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastNameFanaticEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Nombre de Usuario :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 210, 20));

        txtUserNameFanaticEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameFanaticEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserNameFanaticEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, 20));

        txtEmailFanaticEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFanaticEditActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailFanaticEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Equipos favoritos :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 20));

        jcbTeamsFanaticEdit.setEditable(true);
        jcbTeamsFanaticEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcbTeamsFanaticEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameFanaticEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFanaticEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFanaticEditActionPerformed

    private void txtLastNameFanaticEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameFanaticEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFanaticEditActionPerformed

    private void txtUserNameFanaticEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameFanaticEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameFanaticEditActionPerformed

    private void txtEmailFanaticEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFanaticEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFanaticEditActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FanaticView retorno = new FanaticView();
        retorno.show();
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FanaticEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FanaticEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FanaticEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FanaticEditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FanaticEditView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarEdit;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbTeamsFanaticEdit;
    private javax.swing.JTextField txtEmailFanaticEdit;
    private javax.swing.JTextField txtLastNameFanaticEdit;
    private javax.swing.JTextField txtNameFanaticEdit;
    private javax.swing.JTextField txtUserNameFanaticEdit;
    // End of variables declaration//GEN-END:variables
}
