/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import LogRegister.Login;

/**
 *
 * @author tony-
 */
public class FanaticView extends javax.swing.JFrame {

    /**
     * Creates new form FanaticView
     */
    public FanaticView() {
        initComponents();
        setTitle("Plataforma de Fanatico");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerPartido = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNameFanatic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastNameFanatic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserNameFanatic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFanatic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbTeamsFanatic = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerPartido.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnVerPartido.setText("Ver pártidos");
        btnVerPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPartidoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 160, 60));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 160, 60));

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton3.setText("Editar Perfil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 160, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Perfil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 113, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Nombre :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, 20));

        txtNameFanatic.setEditable(false);
        txtNameFanatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFanaticActionPerformed(evt);
            }
        });
        jPanel1.add(txtNameFanatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 220, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Apellido :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, 20));

        txtLastNameFanatic.setEditable(false);
        txtLastNameFanatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameFanaticActionPerformed(evt);
            }
        });
        jPanel1.add(txtLastNameFanatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Nombre de Usuario :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 210, 20));

        txtUserNameFanatic.setEditable(false);
        txtUserNameFanatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameFanaticActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserNameFanatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 220, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Email :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 70, 20));

        txtEmailFanatic.setEditable(false);
        txtEmailFanatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFanaticActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailFanatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Equipos favoritos :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 190, 20));

        jcbTeamsFanatic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jcbTeamsFanatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPartidoActionPerformed
        matchView verpartido =  new matchView();
        verpartido.show();
        this.dispose();
    }//GEN-LAST:event_btnVerPartidoActionPerformed

    private void txtNameFanaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFanaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFanaticActionPerformed

    private void txtLastNameFanaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameFanaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameFanaticActionPerformed

    private void txtUserNameFanaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameFanaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameFanaticActionPerformed

    private void txtEmailFanaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFanaticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailFanaticActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FanaticEditView  editFanatic= new FanaticEditView();
        editFanatic.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login returnLogin= new Login();
        returnLogin.setVisible(true);// Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FanaticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FanaticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FanaticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FanaticView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FanaticView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerPartido;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbTeamsFanatic;
    private javax.swing.JTextField txtEmailFanatic;
    private javax.swing.JTextField txtLastNameFanatic;
    private javax.swing.JTextField txtNameFanatic;
    private javax.swing.JTextField txtUserNameFanatic;
    // End of variables declaration//GEN-END:variables
}
