/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Matches;
import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author arianasaboriom
 */
public class Match extends javax.swing.JFrame {
    private String group;
    private int count_matches = 1;
    /**
     * Creates new form Match
     */
    public Match() {
        this.group = "C";
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Time4label = new javax.swing.JLabel();
        Result4label = new javax.swing.JLabel();
        VS4label = new javax.swing.JLabel();
        Stadium4label = new javax.swing.JLabel();
        VS1label = new javax.swing.JLabel();
        Date5label = new javax.swing.JLabel();
        Stadium1label = new javax.swing.JLabel();
        Time5label = new javax.swing.JLabel();
        Date1label = new javax.swing.JLabel();
        Result5label = new javax.swing.JLabel();
        Time1label = new javax.swing.JLabel();
        VS5label = new javax.swing.JLabel();
        Result1label = new javax.swing.JLabel();
        Stadium5label = new javax.swing.JLabel();
        Date2label = new javax.swing.JLabel();
        Time2label = new javax.swing.JLabel();
        Result2label = new javax.swing.JLabel();
        VS2label = new javax.swing.JLabel();
        Stadium2label = new javax.swing.JLabel();
        Date3label = new javax.swing.JLabel();
        Time3label = new javax.swing.JLabel();
        Result3label = new javax.swing.JLabel();
        VS3label = new javax.swing.JLabel();
        Stadium3label = new javax.swing.JLabel();
        Date4label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DeleteM = new javax.swing.JButton();
        Corresponsal1label = new javax.swing.JLabel();
        Corresponsal2label = new javax.swing.JLabel();
        Corresponsal3label = new javax.swing.JLabel();
        Corresponsal4label = new javax.swing.JLabel();
        Corresponsal5label = new javax.swing.JLabel();
        Result = new javax.swing.JTextField();
        CreateM = new javax.swing.JButton();
        Corresponsal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Country1 = new javax.swing.JTextField();
        Country2 = new javax.swing.JTextField();
        Stadium = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        Country2T = new javax.swing.JTextField();
        LineUp1Text = new javax.swing.JTextField();
        LineUp2Text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        VS6label = new javax.swing.JLabel();
        Stadium6label = new javax.swing.JLabel();
        Date6label = new javax.swing.JLabel();
        Time6label = new javax.swing.JLabel();
        Corresponsal6label = new javax.swing.JLabel();
        Result6label = new javax.swing.JLabel();
        Country1T = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Time4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time4label.setText("Time");
        Time4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result4label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result4label.setText("Result");
        Result4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS4label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS4label.setText("VS");
        VS4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium4label.setText("Stadium");
        Stadium4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS1label.setBackground(new java.awt.Color(255, 255, 255));
        VS1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS1label.setText("VS");
        VS1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date5label.setText("Date");
        Date5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium1label.setBackground(new java.awt.Color(255, 255, 255));
        Stadium1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium1label.setText("Stadium");
        Stadium1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Time5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time5label.setText("Time");
        Time5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date1label.setBackground(new java.awt.Color(255, 255, 255));
        Date1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date1label.setText("Date");
        Date1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result5label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result5label.setText("Result");
        Result5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Time1label.setBackground(new java.awt.Color(255, 255, 255));
        Time1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time1label.setText("Time");
        Time1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS5label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS5label.setText("VS");
        VS5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result1label.setBackground(new java.awt.Color(255, 255, 255));
        Result1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result1label.setText("Result");
        Result1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium5label.setText("Estadium");
        Stadium5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date2label.setText("Date");
        Date2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Time2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time2label.setText("Time");
        Time2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result2label.setText("Result");
        Result2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS2label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS2label.setText("VS");
        VS2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium2label.setText("Stadium");
        Stadium2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date3label.setText("Date");
        Date3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Time3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time3label.setText("Time");
        Time3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result3label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result3label.setText("Result");
        Result3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        VS3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS3label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS3label.setText("VS");
        VS3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium3label.setText("Stadium");
        Stadium3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date4label.setText("Date");
        Date4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("October Compressed Tamil", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 51));
        jLabel11.setText("Group A matches");

        DeleteM.setFont(new java.awt.Font("October Compressed Tamil", 1, 18)); // NOI18N
        DeleteM.setText("Delete Match");
        DeleteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMActionPerformed(evt);
            }
        });

        Corresponsal1label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal1label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal1label.setText("Corresponsal");
        Corresponsal1label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Corresponsal2label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal2label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal2label.setText("Corresponsal");
        Corresponsal2label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Corresponsal3label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal3label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal3label.setText("Corresponsal");
        Corresponsal3label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Corresponsal4label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal4label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal4label.setText("Corresponsal");
        Corresponsal4label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Corresponsal5label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal5label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal5label.setText("Corresponsal");
        Corresponsal5label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result.setText("Result (X-X or Not Defined)");
        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        CreateM.setText("Create");
        CreateM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMActionPerformed(evt);
            }
        });

        Corresponsal.setText("Corresponsal");
        Corresponsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorresponsalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("October Compressed Tamil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("Create Match");

        Country1.setText("Country 1");
        Country1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Country1ActionPerformed(evt);
            }
        });

        Country2.setText("Country 2");
        Country2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Country2ActionPerformed(evt);
            }
        });

        Stadium.setText("Stadium");
        Stadium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StadiumActionPerformed(evt);
            }
        });

        Date.setText("DD/MM/YYYY");
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });

        Time.setText("Time (7pm, 11am...)");
        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });

        Country2T.setText("Country2");

        LineUp1Text.setText("Line-up 1");

        LineUp2Text.setText("Line-up 2");

        jLabel2.setText("-->");

        jLabel3.setText("-->");

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Check Format!");

        VS6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        VS6label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VS6label.setText("VS");
        VS6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Stadium6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Stadium6label.setText("Estadium");
        Stadium6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Date6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Date6label.setText("Date");
        Date6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Time6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Time6label.setText("Time");
        Time6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Corresponsal6label.setBackground(new java.awt.Color(255, 255, 255));
        Corresponsal6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Corresponsal6label.setText("Corresponsal");
        Corresponsal6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Result6label.setFont(new java.awt.Font("October Compressed Tamil", 1, 14)); // NOI18N
        Result6label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result6label.setText("Result");
        Result6label.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Country1T.setText("Country1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VS1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stadium1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Time1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Corresponsal1label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VS2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stadium2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Time2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Result2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Corresponsal2label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VS3label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Stadium3label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Date3label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Time3label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Result3label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Corresponsal3label, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LineUp1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LineUp2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VS4label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stadium4label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date4label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time4label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Corresponsal4label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Result4label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VS5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stadium5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Result5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Corresponsal5label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VS6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stadium6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Result6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Corresponsal6label, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel11))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addGap(455, 455, 455))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CreateM)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Corresponsal, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stadium, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Country1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Country2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DeleteM, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(Country2T)
                            .addComponent(Country1T))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel11)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VS3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stadium3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Time3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Corresponsal3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Result3label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VS1label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stadium1label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date1label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Time1label)
                        .addGap(5, 5, 5)
                        .addComponent(Corresponsal1label)
                        .addGap(6, 6, 6)
                        .addComponent(Result1label))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(Result2label))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Corresponsal2label)
                            .addGap(6, 6, 6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(VS2label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Stadium2label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Date2label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Time2label)
                            .addGap(33, 33, 33)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VS4label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stadium4label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date4label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Time4label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Corresponsal4label)
                        .addGap(6, 6, 6)
                        .addComponent(Result4label))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(VS6label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Stadium6label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Date6label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Time6label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Corresponsal6label)
                            .addGap(3, 3, 3)
                            .addComponent(Result6label))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(VS5label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Stadium5label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Date5label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Time5label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Corresponsal5label)
                            .addGap(3, 3, 3)
                            .addComponent(Result5label))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LineUp1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Country1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LineUp2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(Country2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stadium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(Corresponsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DeleteM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Country1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Country2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jLabel4.hide();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultActionPerformed

    private void CreateMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateMActionPerformed
        // TODO add your handling code here:
        
        //general format
        try{
            if(Country1.getText().equals("Country1") || Country1.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Country2.getText().equals("Country2") || Country2.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Stadium.getText().equals("Stadium") || Stadium.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Date.getText().equals("DD/MM/YYYY") || Date.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Time.getText().equals("Time (7pm, 11am...)") || Time.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Corresponsal.getText().equals("Corresponsal") || Corresponsal.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(Result.getText().equals("Result (X-X or Not Defined)") || Result.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(LineUp1Text.getText().equals("Line-up 1") || LineUp1Text.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            if(LineUp2Text.getText().equals("Line-up 2") || LineUp2Text.getText().equals("")){
                throw new Exception("Empty or default values encountered");
            }
            
        }catch(Exception e){
            System.out.println(e);
            jLabel4.setVisible(true);
            return;
        }
        //try for the date format
        try{
            java.util.Date date34 = null;
            String DateT = Date.getText();
            date34 = new SimpleDateFormat("dd/MM/yyyy").parse(DateT);
        }catch(Exception e){
            System.out.println(e);
            jLabel4.setVisible(true);
            return;
        }
        
        //try for the time format
        try{
            String timeT = Time.getText();
            if(timeT.length() != 3 && timeT.length() != 4){
                throw new Exception("Length of Time, isnt a valid format");
            }
            if(timeT.length() == 3){
            if(!Character.isDigit(timeT.charAt(0))){
                throw new Exception("First character is not a number");
            }
            if( (timeT.charAt(1) != 'a' || timeT.charAt(1) != 'p' )&& timeT.charAt(2) != 'm'){
                throw new Exception("Last characters are neither 'am' or 'pm' ");
            }
            }
            if(timeT.length() == 4){
                if(!Character.isDigit(timeT.charAt(0)) && !Character.isDigit(timeT.charAt(1))){
                throw new Exception("First and second characters are not a number");
            }
            if( (timeT.charAt(2) != 'a' || timeT.charAt(2) != 'p' )&& timeT.charAt(3) != 'm'){
                throw new Exception("Last characters are neither 'am' or 'pm' ");
            }
            }
        }catch(Exception e){
            System.out.println(e);
            jLabel4.setVisible(true);
            return;
        }
        
        //try for the LineUps format
        try{
            //for line2T
            String line1T = LineUp1Text.getText();
            String line2T = LineUp1Text.getText();
            if(line2T.length() != 5){
                throw new Exception("Length not valid");
            }
            if(!Character.isDigit(line2T.charAt(0)) && !Character.isDigit(line2T.charAt(2)) && !Character.isDigit(line2T.charAt(4))){
                throw new Exception("Numbers are not in position 0, 2 and 4");
            }
            if(line2T.charAt(0) == 0 ||line2T.charAt(2) == 0 || line2T.charAt(4) == 0){
                throw new Exception("One or more digits are 0");
            }
            if(line2T.charAt(1) != '-' && line2T.charAt(3) != '-'){
                throw new Exception("There are not hyphens in the required positions");
            }
            int l1T2 = Character.getNumericValue(line2T.charAt(0));
            int l2T2 = Character.getNumericValue(line2T.charAt(2));
            int l3T2 = Character.getNumericValue(line2T.charAt(4));
            if((l1T2+ l2T2 + l3T2) != 10 ){
                throw new Exception("Line up doesnt add up to 10 field players");
            }
            
            //now for line1T
            if(line1T.length() != 5){
                throw new Exception("Length not valid");
            }
            if(line1T.charAt(0) == 0 ||line1T.charAt(2) == 0 || line1T.charAt(4) == 0){
                throw new Exception("One or more digits are 0");
            }
            if(!Character.isDigit(line1T.charAt(0)) && !Character.isDigit(line1T.charAt(2)) && !Character.isDigit(line1T.charAt(4))){
                throw new Exception("Numbers are not in position 0, 2 and 4");
            }
            if(line1T.charAt(1) != '-' && line1T.charAt(3) != '-'){
                throw new Exception("There are not hyphens in the required positions");
            }
            int l1T1 = Character.getNumericValue(line1T.charAt(0));
            int l2T1 = Character.getNumericValue(line1T.charAt(2));
            int l3T1 = Character.getNumericValue(line1T.charAt(4));
            if((l1T1+ l2T1 + l3T1) != 10 ){
                throw new Exception("Line up doesnt add up to 10 field players");
            }
        }catch(Exception e){
            System.out.println(e);
            jLabel4.setVisible(true);
            return;
        }
        
        //try for result format
        try{
            String resultT = Result.getText();
            if(resultT.length() != 3 && !resultT.equals("Not Defined")){
                throw new Exception("Result length not valid");
            } 
            if(resultT.length() == 3){
            if(!Character.isDigit(resultT.charAt(0)) && !Character.isDigit(resultT.charAt(2))){
                throw new Exception("Result format not valid");
            }
            if(resultT.charAt(1) != '-'){
                throw new Exception("Not hyphen in the middle");
            }
            }
            
        }catch(Exception e){
            System.out.println(e);
            jLabel4.setVisible(true);
            return;
        }
        
        //now insert to db
        try{
            System.out.println("HEEERE");getGroup();
            jLabel4.setVisible(false);
            Connection cn = MySQL.MySQLdb.getConnection();
            String sql = "insert into db1. WorldCup (Stage, Country1, Country2, Stadium, Date, Time, Corresponsal, Result, LineUp1, LineUp2) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps;
            ps= cn.prepareStatement(sql);
            String g = "32-StageGroup" +getGroup();
            System.out.println(g);
            ps.setString(1, g); 
            ps.setString(2, Country1.getText());
            ps.setString(3, Country2.getText());
            ps.setString(4, Stadium.getText());
            ps.setString(5, Date.getText());
            ps.setString(6, Time.getText());
            ps.setString(7, Corresponsal.getText());
            ps.setString(8, Result.getText());
            ps.setString(9, LineUp1Text.getText());
            ps.setString(10, LineUp2Text.getText());
            
            ps.execute();
        }catch(Exception e){
            System.out.println(e);
        }
        getInformation();

    }//GEN-LAST:event_CreateMActionPerformed

    public void getInformation(){
        System.out.println("YET");
        System.out.println("GROUP:" + group);
        count_matches = 1;
         try{
            Connection cn = MySQL.MySQLdb.getConnection();
            String sql = "select Country1, Country2, Stadium, Date, Time, Corresponsal, Result from db1. WorldCup where Stage = ? "; 
            PreparedStatement ps;
            ps= cn.prepareStatement(sql);
            
            ps.setString(1, "32-StageGroup" + getGroup());
            
            ResultSet rs = ps.executeQuery();
            
            
            while(rs.next()){
                if(count_matches == 1){
                    VS1label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium1label.setText(rs.getString(3));
                    Date1label.setText(rs.getString(4));
                    Time1label.setText(rs.getString(5));
                    Corresponsal1label.setText(rs.getString(6));
                    Result1label.setText(rs.getString(7));
                    count_matches++;
                    
                }
                else if(count_matches == 2){
                    VS2label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium2label.setText(rs.getString(3));
                    Date2label.setText(rs.getString(4));
                    Time2label.setText(rs.getString(5));
                    Corresponsal2label.setText(rs.getString(6));
                    Result2label.setText(rs.getString(7));
                    count_matches++;
                    
                }
                else if(count_matches == 3){
                    VS3label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium3label.setText(rs.getString(3));
                    Date3label.setText(rs.getString(4));
                    Time3label.setText(rs.getString(5));
                    Corresponsal3label.setText(rs.getString(6));
                    Result3label.setText(rs.getString(7));
                    count_matches++;
                    
                }
                else if(count_matches == 4){
                    VS4label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium4label.setText(rs.getString(3));
                    Date4label.setText(rs.getString(4));
                    Time4label.setText(rs.getString(5));
                    Corresponsal4label.setText(rs.getString(6));
                    Result4label.setText(rs.getString(7));
                    count_matches++;
                    
                }
                else if(count_matches == 5){
                    VS5label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium5label.setText(rs.getString(3));
                    Date5label.setText(rs.getString(4));
                    Time5label.setText(rs.getString(5));
                    Corresponsal5label.setText(rs.getString(6));
                    Result5label.setText(rs.getString(7));
                    count_matches++;
                    
                }
                else if(count_matches == 6){
                    VS6label.setText(rs.getString(1) + " VS " + rs.getString(2));
                    Stadium6label.setText(rs.getString(3));
                    Date6label.setText(rs.getString(4));
                    Time6label.setText(rs.getString(5));
                    Corresponsal6label.setText(rs.getString(6));
                    Result6label.setText(rs.getString(7));
                    count_matches = 1;
                    
                }
                
                //System.out.println("LastName: " + rs.getString(1));
                //System.out.println("FirstName: " + rs.getString(2));
                //System.out.println("EmailAddress: " + rs.getString(3));
                //System.out.println("Username: " + rs.getString(4)); 
            }
            
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void CorresponsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorresponsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorresponsalActionPerformed

    private void Country1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Country1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Country1ActionPerformed

    private void Country2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Country2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Country2ActionPerformed

    private void StadiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StadiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StadiumActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeActionPerformed

    private void DeleteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = MySQL.MySQLdb.getConnection();
            String sql = "delete from db1. WorldCup where Stage = ? and Country1 = ? and Country2 = ?"; 
            PreparedStatement ps;
            ps= cn.prepareStatement(sql);
            
            ps.setString(1, "32-StageGroup"+getGroup());
            ps.setString(2, Country1T.getText());
            ps.setString(3, Country2T.getText());
            
            ps.execute();
            
            //update information in labels
            count_matches = 1;
            setDefaultValues();
            
            
            
        }catch(Exception e){
            System.out.println(e);
        }
        
        getInformation();
    }//GEN-LAST:event_DeleteMActionPerformed

    public String getGroup() {
        System.out.println("Group NOW: " + group);
        return group;
    }
    
/*
    public void setGroup(String group){
        this.group = group;
        jLabel11.setText("Group " + group + " Matches");
        System.out.println("Group set to : " + group);
        
    }
    public String getGroup(){
        System.out.println("Group NOW: " + this.group);
        return this.group;
    }
    */

    public void setGroup(String group) {
        this.group = group;
        jLabel11.setText("Group " + group + " Matches");
        System.out.println("Group set to : " + group);
        getInformation();
    }
    
    
    
    private void setDefaultValues(){
        VS1label.setText(" VS ");
        Stadium1label.setText("Stadium");
        Date1label.setText("Date");
        Time1label.setText("Time");
        Corresponsal1label.setText("Corresponsal");
        Result1label.setText("Result");
        
        VS2label.setText(" VS ");
        Stadium2label.setText("Stadium");
        Date2label.setText("Date");
        Time2label.setText("Time");
        Corresponsal2label.setText("Corresponsal");
        Result2label.setText("Result");
        
        VS3label.setText(" VS ");
        Stadium3label.setText("Stadium");
        Date3label.setText("Date");
        Time3label.setText("Time");
        Corresponsal3label.setText("Corresponsal");
        Result3label.setText("Result");
        
        VS4label.setText(" VS ");
        Stadium4label.setText("Stadium");
        Date4label.setText("Date");
        Time4label.setText("Time");
        Corresponsal4label.setText("Corresponsal");
        Result4label.setText("Result");
        
        VS5label.setText(" VS ");
        Stadium5label.setText("Stadium");
        Date5label.setText("Date");
        Time5label.setText("Time");
        Corresponsal5label.setText("Corresponsal");
        Result5label.setText("Result");
        
        VS6label.setText(" VS ");
        Stadium6label.setText("Stadium");
        Date6label.setText("Date");
        Time6label.setText("Time");
        Corresponsal6label.setText("Corresponsal");
        Result6label.setText("Result");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Match.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Corresponsal;
    private javax.swing.JLabel Corresponsal1label;
    private javax.swing.JLabel Corresponsal2label;
    private javax.swing.JLabel Corresponsal3label;
    private javax.swing.JLabel Corresponsal4label;
    private javax.swing.JLabel Corresponsal5label;
    private javax.swing.JLabel Corresponsal6label;
    private javax.swing.JTextField Country1;
    private javax.swing.JTextField Country1T;
    private javax.swing.JTextField Country2;
    private javax.swing.JTextField Country2T;
    private javax.swing.JButton CreateM;
    private javax.swing.JTextField Date;
    private javax.swing.JLabel Date1label;
    private javax.swing.JLabel Date2label;
    private javax.swing.JLabel Date3label;
    private javax.swing.JLabel Date4label;
    private javax.swing.JLabel Date5label;
    private javax.swing.JLabel Date6label;
    private javax.swing.JButton DeleteM;
    private javax.swing.JTextField LineUp1Text;
    private javax.swing.JTextField LineUp2Text;
    private javax.swing.JTextField Result;
    private javax.swing.JLabel Result1label;
    private javax.swing.JLabel Result2label;
    private javax.swing.JLabel Result3label;
    private javax.swing.JLabel Result4label;
    private javax.swing.JLabel Result5label;
    private javax.swing.JLabel Result6label;
    private javax.swing.JTextField Stadium;
    private javax.swing.JLabel Stadium1label;
    private javax.swing.JLabel Stadium2label;
    private javax.swing.JLabel Stadium3label;
    private javax.swing.JLabel Stadium4label;
    private javax.swing.JLabel Stadium5label;
    private javax.swing.JLabel Stadium6label;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel Time1label;
    private javax.swing.JLabel Time2label;
    private javax.swing.JLabel Time3label;
    private javax.swing.JLabel Time4label;
    private javax.swing.JLabel Time5label;
    private javax.swing.JLabel Time6label;
    private javax.swing.JLabel VS1label;
    private javax.swing.JLabel VS2label;
    private javax.swing.JLabel VS3label;
    private javax.swing.JLabel VS4label;
    private javax.swing.JLabel VS5label;
    private javax.swing.JLabel VS6label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
